server:
  port: ":8080"

mysql:
  dbuser: john
  dbpassword: 1111
  dbhost: localhost
  dbport: 3306
  dbname: nft_platform

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

contract:
  eth_rpc_url: "http://localhost:8545"
  usrAddress: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
  privateKey: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
  contractAddress: "0x71C95911E9a5D330f4D621842EC243EE1343292e"
  contractApiFile: "~/project/EduNovaChain/Contract/out/nft.sol/EducationInnovationNFT.json"

jwtSecret: "c2f7e3b6f88c4e1b8d9252f3d7c74eae63f2b41e519f2e9a75c7685c4b7e89a2"

ipfsApiKey: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkNmM1Y2M0MS1hZmIxLTQwOGYtOGUzNi0yZTRjZWRlNTM0YTEiLCJlbWFpbCI6Imxvbmd5dTAxMTZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiRlJBMSJ9LHsiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiTllDMSJ9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6Ijk4ODY2MTNmYmRmOTAwZWI1YjZlIiwic2NvcGVkS2V5U2VjcmV0IjoiMDNkZDI4YTcxOWE0YzAyMTlhNmFjOWMyMzY5YzI4MzIxMzk3ZTM3OWI2ZjAxYWMwY2NiNTQ3Njc1MDlmNDM4MiIsImV4cCI6MTc1NjU2ODA3N30.yPzKqAbu49PX3HZadUuHtY-hIpYB-bqZatjIzgOJCx0"