import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import LoginButton from "./components/LoginButton";
import { cookies } from "next/headers";
import WagmiContext from "./context/WagmiContext";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Header from "./components/header/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const email = cookies().get("email")?.value ?? "";

  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiContext>
          <Header />

          <section className="mx-auto max-w-4xl px-4 py-6 text-[#333] sm:px-6 sm:py-6 lg:max-w-7xl lg:px-8">
            {/* <ConnectButton /> */}
            {children}
            {modal}
          </section>

          <footer className="p-4 w-full mt-6 bg-primary text-gray-300">
            <div className="text-center text-sm font-light">
              Copyright © 2024 {process.env.NEXT_PUBLIC_APP_NAME}.All Rights
              Reserved.
            </div>
          </footer>
        </WagmiContext>
      </body>
    </html>
  );
}
